import socket
import sys
from Crypto.Cipher import AES

def encrypt(encrypt_data):
	obj = AES.new(b"1122334456789001" , AES.MODE_CFB, b"2299225510784791")
	data = obj.encrypt(encrypt_data)
	return data

def decrypt(decrypt_data):
        obj = AES.new(b"1122334456789001" , AES.MODE_CFB, b"2299225510784791")
        data = obj.decrypt(decrypt_data)
        return data


ServerIp = "192.168.14.10"

s = socket.socket()
PORT = 9898
s.connect((ServerIp, PORT))

print ("\n Connected to the Server !! ")

loop = 1
while loop == 1:
	userF = input("\n Enter the file name : ")
	try:
		file = open(userF, "rb")
		loop = -1

		print ("\n Before Encryption : " + str(userF) )
		encrypted = encrypt(userF.encode())
		print ("\n After Encryption : " + str(encrypted) )
		s.send(encrypted)

	except IOError:
		print ("\n Can't open pls try again !")

SendData = file.read(1024)
while SendData:
	msg = s.recv(1024)
	temp = decrypt(msg)

	print("\n\n ################## Below message is generated by Server..  ################## \n\n ",temp.decode())
	#Sending file

	encrypted = encrypt(SendData)
	s.send(encrypted)

	SendData = file.read(1024)

s.close()
